#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'nose==1.0.0','console_scripts','nosetests'
import gevent
import gevent.monkey
gevent.monkey.patch_all()
__requires__ = 'nose==1.0.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('nose==1.0.0', 'console_scripts', 'nosetests')()
    )
